#!/bin/sh

# run tests
python -m unittest discover -s LinkChecker
TEST_RESULT=$?

# run pyflakes
pyflakes .
PYFLAKES_RESULT=$?

if [[ "$TEST_RESULT" -eq 1 ]] || [[ "$PYFLAKES_RESULT" -eq 1 ]]
then
  echo ""
  echo "**********************"
  echo "*** Commit blocked ***"
  echo "**********************"
  exit 1
fi

exit 0
