#!/bin/sh

# run tests
python -m unittest discover -s LinkChecker
TEST_RESULT=$?

# run pyflakes
pyflakes .
PYFLAKES_RESULT=$?

# python test runner will set exit code appropriately
if ($TEST_RESULT || $PYFLAKES_RESULT); then
  exit 1
fi

exit 0
